„alpine/alpine-tools“ ändern

diff --git a/alpine/alpine-tools b/alpine/alpine-tools
--- a/alpine/alpine-tools
+++ b/alpine/alpine-tools
@@ -1,4 +1,4 @@
-FROM alpine:latest
+FROM alcapone1933/alpine:latest
 LABEL maintainer="alcapone1933 <alcapone1933@cosanostra-cloud.de>" \
       org.opencontainers.image.created="$(date +%Y-%m-%d\ %H:%M)" \
       org.opencontainers.image.authors="alcapone1933 <alcapone1933@cosanostra-cloud.de>"
@@ -9,12 +9,30 @@ WORKDIR /root
 
 RUN apk add --update --no-cache bash sudo byobu tini tzdata curl wget git tig nano bind-tools gnupg jq python3 py3-pip \
     netcat-openbsd iputils nmap net-tools openssh-client openssl iperf iproute2 procps vnstat mtr tcptraceroute tcpdump speedtest-cli docker ca-certificates libc6-compat hstr ncurses bash-completion && \
-    wget -q -O - https://raw.githubusercontent.com/alcapone1933/shell-scripts/master/install/docker-compose-install.sh | sudo bash && \
     git clone --depth=1 https://github.com/Bash-it/bash-it.git /root/.bash_it && /root/.bash_it/install.sh --silent && \
     rm -rf /var/cache/apk/* && \
     ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
-
-RUN sed -i "s/export BASH_IT_THEME='bobby'/export BASH_IT_THEME='zork'/g" /root/.bashrc && \
+RUN set -eux && \
+    COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4) && \
+    apkArch="$(apk --print-arch)" && \
+    case "$apkArch" in \
+		'x86_64') \
+			url='https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-x86_64'; \
+			;; \
+		'armhf') \
+			url='https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-armv6'; \
+			;; \
+		'armv7') \
+			url='https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-armv7'; \
+			;; \
+		'aarch64') \
+			url='https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-aarch64'; \
+			;; \
+		*) echo >&2 "error: unsupported 'docker-compose' architecture ($apkArch)"; exit 1 ;; \
+    esac && \
+    echo "$url = $(apk --print-arch)" && \
+    sh -c "curl -L $url > /usr/local/bin/docker-compose" && chmod +x /usr/local/bin/docker-compose && \
+    sed -i "s/export BASH_IT_THEME='bobby'/export BASH_IT_THEME='zork'/g" /root/.bashrc && \
     sed -i "s/export GIT_HOSTING='git@git.domain.com'/# export GIT_HOSTING='git@git.domain.com'/g" /root/.bashrc && \
     sed -i "s/export IRC_CLIENT='irssi'/# export IRC_CLIENT='irssi'/g" /root/.bashrc && \
     sed -i "s/export TODO=/# export TODO/g" /root/.bashrc && \
